# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b14085ea19707cba01e542ea8f61c9cec4385d27340e1187f36c7cb1c0f3b287752c549c4524d42266eaec89f03715616d1d726c4fbdb1d4376d308d088ead

test:
  secret_key_base: 1140b3733a470f95e8ccbba7e86f77fa5d5be9583bd2c6ecd613f4722382f94b9bf77a7c261418a4ba5be7af46b547209d3cb02e84e974c93afc2af99209becc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
